import { RLAgent } from './RLAgent.js';
import { GameHelpers } from '../utils/GameHelpers.js';

// Always-on committed joint-goal choice.
// - Maintain P_intent(joint goal) inferred from observed actions using joint-RL likelihood.
// - From the beginning of the trial, sample every step from:
//     W_lambda(g) ∝ exp(beta * EU(g)) * P_intent(g)^lambda
// - Movement is generated by joint-RL restricted to the sampled joint goal.

export class AlwaysCommittedAgent {
  constructor(options = {}) {
    this.rl = options.rlAgent || new RLAgent();
    this.lambda = (typeof options.lambda === 'number') ? options.lambda : 1.0;
    this.beta = (typeof options.beta === 'number') ? options.beta : 3.0;
    this.eps = 1e-6;
    this.reset();
  }

  reset() {
    this._lastTrialKey = null;
    this._pIntent = null;
    this._lastObservedStep = -1;
  }

  getAIAction(gameState, trialData, aiPlayerNumber = 2) {
    const goals = Array.isArray(gameState?.currentGoals) ? gameState.currentGoals : [];
    if (!goals.length) return [0, 0];

    const aiPos = (aiPlayerNumber === 1) ? gameState?.player1 : gameState?.player2;
    const otherPos = (aiPlayerNumber === 1) ? gameState?.player2 : gameState?.player1;
    if (!aiPos || !otherPos) return [0, 0];

    const trialKey = `${String(gameState?.experimentType || '')}:${Number.isFinite(gameState?.trialIndex) ? gameState.trialIndex : 'na'}`;
    if (this._lastTrialKey !== trialKey) {
      this.reset();
      this._lastTrialKey = trialKey;
    }

    this._ensurePosterior(goals);
    this._bayesUpdateFromObservedActions(gameState, trialData, goals);

    const weights = this._combinedWeights(goals, aiPos, otherPos);
    const goalIdx = this._sampleFromWeights(weights);
    this._recordSample(trialData, aiPlayerNumber, goalIdx, weights);

    const goal = goals[goalIdx];
    if (!Array.isArray(goal) || goal.length < 2) return [0, 0];
    return this.rl.getJointRLAction(aiPos, otherPos, [goal]);
  }

  _recordSample(trialData, aiPlayerNumber, goalIdx, weights) {
    if (!trialData) return;
    try {
      const playerPrefix = aiPlayerNumber === 1 ? 'alwaysCommittedAgentPlayer1' : 'alwaysCommittedAgentPlayer2';
      const sample = {
        step: this._inferCurrentStepIndex(trialData),
        goal: goalIdx,
        posterior: this._pIntent ? this._pIntent.slice() : null,
        weights: weights.slice(),
        alwaysCommitted: true,
        everyStepResampling: true
      };
      trialData.alwaysCommittedAgentSampledJointGoal = goalIdx;
      trialData.alwaysCommittedAgentSampledJointGoalPosterior = this._pIntent ? this._pIntent.slice() : null;
      trialData.alwaysCommittedAgentSampledJointGoalWeights = weights.slice();
      trialData[`${playerPrefix}SampledJointGoal`] = goalIdx;
      trialData[`${playerPrefix}SampledJointGoalPosterior`] = this._pIntent ? this._pIntent.slice() : null;
      trialData[`${playerPrefix}SampledJointGoalWeights`] = weights.slice();
      const historyKey = `${playerPrefix}SampledJointGoalHistory`;
      if (!Array.isArray(trialData[historyKey])) trialData[historyKey] = [];
      trialData[historyKey].push(sample);
    } catch (_) { /* noop */ }
  }

  _inferCurrentStepIndex(trialData) {
    try {
      const a1 = Array.isArray(trialData?.player1Actions) ? trialData.player1Actions.length : 0;
      const a2 = Array.isArray(trialData?.player2Actions) ? trialData.player2Actions.length : 0;
      return Math.max(a1, a2);
    } catch (_) {
      return null;
    }
  }

  _ensurePosterior(goals) {
    const n = goals.length;
    if (!this._pIntent || !Array.isArray(this._pIntent)) {
      this._pIntent = new Array(n).fill(1 / n);
      this._lastObservedStep = -1;
      return;
    }
    if (this._pIntent.length !== n) {
      this._pIntent = this._resizePosterior(this._pIntent, n);
      this._normalizePosterior(this._pIntent);
    }
  }

  _resizePosterior(oldPosterior, n) {
    const old = Array.isArray(oldPosterior) ? oldPosterior : [];
    if (!old.length) return new Array(n).fill(1 / n);

    const next = new Array(n).fill(0);
    const m = Math.min(old.length, n);
    const oldTotal = old.slice(0, m).reduce((a, b) => a + (isFinite(b) ? b : 0), 0);
    const added = Math.max(0, n - old.length);
    const newGoalMass = added > 0 ? added / n : 0;
    const oldMass = Math.max(0, 1 - newGoalMass);

    for (let i = 0; i < m; i++) {
      next[i] = oldTotal > 0 ? (old[i] / oldTotal) * oldMass : oldMass / m;
    }
    if (added > 0) {
      const perNewGoal = 1 / n;
      for (let i = old.length; i < n; i++) next[i] = perNewGoal;
    }
    return next;
  }

  _bayesUpdateFromObservedActions(gameState, trialData, goals) {
    if (!trialData) return;
    const p1A = Array.isArray(trialData.player1Actions) ? trialData.player1Actions : [];
    const p2A = Array.isArray(trialData.player2Actions) ? trialData.player2Actions : [];
    const p1T = Array.isArray(trialData.player1Trajectory) ? trialData.player1Trajectory : [];
    const p2T = Array.isArray(trialData.player2Trajectory) ? trialData.player2Trajectory : [];

    const maxSteps = Math.max(p1A.length, p2A.length);
    if (maxSteps <= 0) return;

    for (let t = this._lastObservedStep + 1; t < maxSteps; t++) {
      for (let g = 0; g < goals.length; g++) {
        let like = 1.0;
        const goal = goals[g];
        if (Array.isArray(p1A[t]) && Array.isArray(p1T[t]) && Array.isArray(p2T[t])) {
          like *= this._actionLikelihood(p1T[t], p2T[t], p1A[t], goal);
        }
        if (Array.isArray(p2A[t]) && Array.isArray(p2T[t]) && Array.isArray(p1T[t])) {
          like *= this._actionLikelihood(p2T[t], p1T[t], p2A[t], goal);
        }
        this._pIntent[g] *= like;
      }
      this._normalizePosterior(this._pIntent);
      this._lastObservedStep = t;
    }

    try {
      trialData.alwaysCommittedGoalPosterior = this._pIntent.slice();
    } catch (_) { /* noop */ }
  }

  _actionLikelihood(pos, otherPos, action, goal) {
    const probs = this.rl.getJointActionProbabilities(pos, otherPos, [goal]);
    const key = Array.isArray(action) ? action.toString() : String(action || '');
    const p = probs && typeof probs === 'object' ? probs[key] : null;
    if (typeof p === 'number' && isFinite(p) && p > 0) return p;
    return this.eps;
  }

  _normalizePosterior(posterior = this._pIntent) {
    if (!Array.isArray(posterior) || !posterior.length) return;
    const sum = posterior.reduce((a, b) => a + (isFinite(b) ? b : 0), 0);
    if (!isFinite(sum) || sum <= 0) {
      const n = posterior.length || 1;
      for (let i = 0; i < n; i++) posterior[i] = 1 / n;
      return;
    }
    for (let i = 0; i < posterior.length; i++) posterior[i] = posterior[i] / sum;
  }

  _combinedWeights(goals, aiPos, otherPos) {
    const eus = goals.map((g) => this._euJointDistance(aiPos, otherPos, g));
    const scaled = eus.map((eu) => (isFinite(eu) ? this.beta * eu : -Infinity));
    const finiteScaled = scaled.filter((v) => isFinite(v));
    const maxScaled = finiteScaled.length ? Math.max(...finiteScaled) : 0;
    const out = new Array(goals.length).fill(0);
    for (let i = 0; i < goals.length; i++) {
      const pi = (this._pIntent && this._pIntent[i] != null) ? this._pIntent[i] : (1 / goals.length);
      const euWeight = isFinite(scaled[i]) ? Math.exp(Math.max(-700, Math.min(700, scaled[i] - maxScaled))) : 0;
      out[i] = euWeight * Math.pow(Math.max(this.eps, pi), this.lambda);
    }
    const sum = out.reduce((a, b) => a + b, 0) || 0;
    if (sum > 0) return out.map(w => w / sum);
    return new Array(goals.length).fill(1 / goals.length);
  }

  _sampleFromWeights(weights) {
    const sum = weights.reduce((a, b) => a + (isFinite(b) ? b : 0), 0);
    if (!isFinite(sum) || sum <= 0) return 0;
    const r = Math.random() * sum;
    let acc = 0;
    for (let i = 0; i < weights.length; i++) {
      acc += weights[i];
      if (r < acc) return i;
    }
    return weights.length - 1;
  }

  _euJointDistance(aiPos, otherPos, goalPos) {
    const dAi = GameHelpers.calculateGridDistance(aiPos, goalPos);
    const dOther = GameHelpers.calculateGridDistance(otherPos, goalPos);
    const joint = dAi + dOther;
    if (!Number.isFinite(joint)) return -Infinity;
    return -joint;
  }
}
