#!/bin/bash

# Demo script to show GPT prompt debugging in action
# This script demonstrates the enhanced logging output

echo "🔍 GPT Prompt Debugging Demo"
echo "=============================="
echo ""
echo "This script demonstrates the enhanced GPT prompt logging."
echo "When you run the game with GPT debugging enabled, you'll see:"
echo ""
echo "1. 📝 EXACT PROMPT - The complete prompt sent to GPT"
echo "2. 🤖 EXACT RESPONSE - The raw response from GPT"
echo "3. ⚡ FINAL ACTION - The processed action decision"
echo ""
echo "To enable GPT debugging, run:"
echo "  ./enable-gpt-debug.sh"
echo ""
echo "Or manually set the environment variable:"
echo "  export ENABLE_GPT_DEBUG=true"
echo "  npm run dev"
echo ""
echo "The debug output will appear in the terminal when GPT makes moves."
echo "Look for sections marked with '=' characters for easy identification."
echo ""
echo "Example sections you'll see:"
echo "  ================================================================================"
echo "  [GPT PROMPT] EXACT PROMPT SENT TO GPT:"
echo "  ================================================================================"
echo "  [Your complete prompt here]"
echo "  ================================================================================"
echo ""
echo "  ============================================================"
echo "  [GPT RESPONSE] EXACT RESPONSE FROM GPT:"
echo "  ============================================================"
echo "  Raw response: \"right\""
echo "  ============================================================"
echo ""
echo "Ready to see GPT debugging in action!"
echo "Run './enable-gpt-debug.sh' to start the server with debugging enabled."
